use_frameworks!

platform :ios, '8.0'

target 'changxiaobin_Example' do
  pod 'changxiaobin', :path => '../'

  target 'changxiaobin_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
